import { Dimensions, StyleSheet } from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fff" },
  whiteContainer: { flex: 1, backgroundColor: "#fff" },
  authContainer: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    padding: 35,
  },
  authLogo: {
    fontSize: 42,
    fontWeight: "900",
    color: "black",
    marginBottom: 5,
  },
  authSubtext: {
    fontSize: 15,
    color: "black",
    marginBottom: 30,
  },
  authInput: {
    width: "100%",
    height: 45,
    backgroundColor: "#D9D9D9",
    borderRadius: 8,
    paddingHorizontal: 15,
    marginBottom: 12,
  },
  authPrimaryBtn: {
    width: "100%",
    height: 45,
    backgroundColor: "#4A81D3",
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 15,
  },
  authSecondaryBtn: {
    width: "100%",
    height: 45,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#DDD",
  },
  authBtnText: { color: "white", fontSize: 16, fontWeight: "700" },
  authSecondaryText: { color: "#4A81D3", fontSize: 16, fontWeight: "600" },
  authLinkSmall: { fontSize: 12, color: "#666", marginTop: 15 },
  authFooter: { flexDirection: "row", marginTop: 10 },
  authFooterText: { fontSize: 12, color: "#666" },
  authLinkBlue: { fontSize: 12, color: "#4A81D3", fontWeight: "bold" },
  authRow: { flexDirection: "row", width: "100%" },
  emptyGroupsContainer: {
    alignItems: "center",
    paddingVertical: 60,
    paddingHorizontal: 40,
  },
  emptyGroupsTitle: {
    fontSize: 22,
    fontWeight: "bold",
    marginTop: 20,
    color: "#333",
  },
  emptyGroupsText: {
    fontSize: 15,
    color: "#888",
    textAlign: "center",
    marginTop: 8,
    lineHeight: 22,
    marginBottom: 25,
  },
  joinGroupsBtn: {
    backgroundColor: "#4A81D3",
    paddingHorizontal: 30,
    paddingVertical: 12,
    borderRadius: 25,
  },
  joinGroupsBtnText: { color: "white", fontSize: 16, fontWeight: "600" },
  map: { ...StyleSheet.absoluteFillObject },
  header: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  brandText: { fontSize: 24, fontWeight: "900" },
  headerIcons: { flexDirection: "row", gap: 18 },
  leftActionStack: { position: "absolute", bottom: 110, left: 20, gap: 10 },
  circularActionBtn: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
    elevation: 5,
  },
  searchHeaderTop: { paddingTop: 60, paddingHorizontal: 15, paddingBottom: 10 },
  searchField: {
    height: 45,
    backgroundColor: "#F2F2F2",
    borderRadius: 10,
    paddingHorizontal: 15,
    fontSize: 16,
  },
  sectionHeader: { paddingHorizontal: 15, marginTop: 15 },
  sectionTitleText: { fontSize: 24, fontWeight: "700", color: "#333" },
  discoverTagsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 10,
    marginTop: 15,
    gap: 8,
  },
  tagBadge: {
    backgroundColor: "#F2F2F2",
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 25,
  },
  tagText: { fontSize: 14, color: "#444" },
  searchSectionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 15,
    marginTop: 30,
    marginBottom: 15,
  },
  rowAlign: { flexDirection: "row", alignItems: "center" },
  linkTextGray: { color: "#999", fontSize: 15, marginRight: 5 },
  noResultContainer: {
    alignItems: "center",
    paddingVertical: 40,
    paddingHorizontal: 40,
  },
  noResultMainText: { fontSize: 22, fontWeight: "bold", marginTop: 15 },
  noResultSubText: {
    fontSize: 14,
    color: "#888",
    textAlign: "center",
    marginTop: 8,
    lineHeight: 22,
  },
  groupCard: {
    backgroundColor: "#fff",
    marginHorizontal: 15,
    marginBottom: 18,
    borderRadius: 14,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#EEE",
  },
  groupImage: { width: "100%", height: 190 },
  groupInfo: { padding: 14 },
  groupRow: { flexDirection: "row", alignItems: "center" },
  groupLogo: { width: 52, height: 52, borderRadius: 26, marginRight: 14 },
  groupTitle: { fontSize: 18, fontWeight: "700", color: "#111" },
  groupMetaRow: { flexDirection: "row", marginTop: 6, gap: 12 },
  groupMeta: { color: "#777", fontSize: 14 },
  addPostMain: {
    flex: 1,
    paddingTop: 100,
    paddingHorizontal: 25,
    alignItems: "center",
  },
  addPostTitle: { fontSize: 28, fontWeight: "bold", marginBottom: 12 },
  addPostSubtitle: {
    fontSize: 15,
    color: "#666",
    textAlign: "center",
    marginBottom: 40,
  },
  addCard: {
    width: "100%",
    backgroundColor: "#D9D9D9",
    borderRadius: 15,
    flexDirection: "row",
    padding: 18,
    alignItems: "center",
    marginBottom: 15,
  },
  iconBox: {
    width: 60,
    height: 60,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  cardInfo: { flex: 1, marginLeft: 15 },
  cardLabel: { fontSize: 18, fontWeight: "bold" },
  cardSub: { fontSize: 12, color: "#555", marginTop: 2 },
  tabBar: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    height: 85,
    backgroundColor: "white",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingBottom: 25,
    borderTopWidth: 0.5,
    borderTopColor: "#EEE",
  },
  topPageHeader: {
    paddingTop: 65,
    paddingHorizontal: 22,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  topPageTitle: { fontSize: 20, fontWeight: "700", color: "black" },
  emptyStateWrapper: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: -120,
  },
  emptyStateText: {
    marginTop: 15,
    fontSize: 18,
    color: "black",
    fontWeight: "500",
  },
  bottomProfile: { width: 32, height: 32, borderRadius: 16 },
  profileCoverWrapper: { position: "relative" },
  profileCover: { width: "100%", height: 250 },
  emptyCoverOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.05)",
  },
  emptyCoverText: {
    marginTop: 8,
    color: "#999",
    fontSize: 14,
    fontWeight: "500",
  },
  profileTopOverlay: {
    position: "absolute",
    top: 55,
    left: 20,
    right: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  profileTopActions: {
    backgroundColor: "white",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  profileFire: { fontSize: 14, fontWeight: "700", color: "#E91E63" },
  profileAvatarWrapper: {
    width: 130,
    height: 130,
    borderRadius: 65,
    borderWidth: 4,
    borderColor: "white",
    position: "absolute",
    left: 20,
    bottom: -45,
    overflow: "hidden",
    backgroundColor: "#FFF",
    elevation: 4,
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  profileAvatar: { width: "100%", height: "100%", borderRadius: 65 },
  emptyAvatar: {
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: "#F5F5F5",
    justifyContent: "center",
    alignItems: "center",
  },
  profileStatsRow: {
    marginTop: 15,
    flexDirection: "row",
    justifyContent: "space-around",
    paddingLeft: 145,
    paddingRight: 10,
  },
  profileStatItem: { alignItems: "center" },
  profileStatNumber: { fontSize: 20, fontWeight: "bold", color: "#111" },
  profileStatLabel: { fontSize: 12, color: "#888", marginTop: 2 },
  profileContent: { paddingHorizontal: 18, marginTop: 25 },
  profileName: { fontSize: 22, fontWeight: "bold", color: "#111" },
  profileUsername: { fontSize: 15, color: "#999", marginTop: 2 },
  profileBio: { fontSize: 15, color: "#333", marginTop: 15, lineHeight: 22 },
  emptyBio: {
    marginTop: 20,
    padding: 20,
    backgroundColor: "#F8F9FA",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E9ECEF",
    alignItems: "center",
  },
  emptyBioText: { color: "#999", fontSize: 14 },
  profileCars: { fontSize: 18, color: "#222", lineHeight: 32, marginTop: 22 },
  profileCarItem: { fontSize: 15, color: "#333", marginTop: 5 },
  ownedHeader: { marginTop: 25 },
  ownedTitle: { fontSize: 18, fontWeight: "bold", color: "#111" },
  ownedSub: { color: "#999", fontSize: 13, marginTop: 2 },
  vehicleCardsRow: {
    flexDirection: "row",
    marginTop: 15,
    justifyContent: "flex-start",
    gap: 12,
  },
  vehicleCard: {
    width: width * 0.42,
    height: 160,
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: "#DDD",
  },
  emptyVehicleCard: {
    backgroundColor: "#F8F9FA",
    borderWidth: 2,
    borderColor: "#E9ECEF",
    borderStyle: "dashed",
  },
  emptyVehicleText: {
    fontSize: 18,
    fontWeight: "600",
    color: "#6C757D",
    textAlign: "center",
    lineHeight: 28,
  },
  vehicleImage: { width: "100%", height: "100%" },
  ownBadge: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: "#DDEEFF",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  ownBadgeText: { color: "#4A81D3", fontWeight: "bold", fontSize: 11 },
  vehicleOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    padding: 10,
  },
  vehicleName: { color: "white", fontSize: 15, fontWeight: "bold" },
  vehicleModel: { color: "rgba(255,255,255,0.8)", fontSize: 11, marginTop: 2 },
  showAllCard: {
    width: width * 0.42,
    height: 160,
    borderRadius: 16,
    backgroundColor: "#F2F2F2",
    justifyContent: "center",
    alignItems: "center",
    padding: 10,
  },
  showAllText: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#111",
    textAlign: "center",
    lineHeight: 22,
  },
  vehicleTab: {
    marginTop: 20,
    backgroundColor: "#F2F2F2",
    alignSelf: "flex-start",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  vehicleTabText: { fontSize: 13, color: "#333", fontWeight: "600" },
  postTitle: { marginTop: 25, fontSize: 18, fontWeight: "bold", color: "#111" },
  feedContainer: { flex: 1, backgroundColor: "#F9F9F9" },
  groupDetailTopBar: {
    position: "absolute",
    top: 50,
    left: 15,
    right: 15,
    flexDirection: "row",
    justifyContent: "space-between",
    zIndex: 10,
  },
  groupDetailTopBtn: {
    backgroundColor: "white",
    padding: 10,
    borderRadius: 25,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  groupDetailTopRight: {
    backgroundColor: "white",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  verticalDivider: {
    width: 1,
    height: 18,
    backgroundColor: "#CCC",
    marginHorizontal: 12,
  },
  groupCoverPhoto: { width: "100%", height: 220 },
  groupInfoContainer: {
    paddingHorizontal: 15,
    paddingBottom: 15,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#EAEAEA",
  },
  avatarTagRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginTop: -45,
  },
  groupAvatarWrapper: {
    width: 90,
    height: 90,
    borderRadius: 45,
    borderWidth: 4,
    borderColor: "white",
    overflow: "hidden",
    backgroundColor: "#EEE",
  },
  groupAvatarImage: { width: "100%", height: "100%" },
  groupTagBadgeDetailed: {
    backgroundColor: "#1E88E5",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    marginBottom: 10,
  },
  groupTagTextDetailed: { color: "white", fontWeight: "bold", fontSize: 13 },
  groupDetailTitle: {
    fontSize: 26,
    fontWeight: "bold",
    color: "#111",
    marginTop: 10,
  },
  groupDetailMetaRow: { flexDirection: "row", marginTop: 6 },
  groupDetailMetaText: { color: "#666", fontSize: 15 },
  groupDetailBioText: {
    fontSize: 15,
    color: "#333",
    marginTop: 14,
    lineHeight: 22,
  },
  groupDetailLinkText: {
    fontSize: 15,
    color: "#1E88E5",
    fontWeight: "600",
    marginTop: 6,
  },
  inviteButton: {
    backgroundColor: "#2196F3",
    width: "100%",
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 20,
  },
  inviteButtonText: { color: "white", fontSize: 16, fontWeight: "bold" },
  groupTabsScroll: { flexDirection: "row", marginTop: 20, marginBottom: 5 },
  groupTabPill: {
    backgroundColor: "#F2F2F2",
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 20,
    marginRight: 10,
  },
  groupTabActivePill: {
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: "#DDD",
  },
  groupTabActiveText: { color: "#333", fontWeight: "700", fontSize: 14 },
  groupTabTextDetailed: { color: "#666", fontWeight: "600", fontSize: 14 },

  fabCreatePost: {
    position: "absolute",
    bottom: 25,
    right: 20,
    width: 60,
    height: 60,
    backgroundColor: "#2196F3",
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },

  postCard: {
    backgroundColor: "#fff",
    marginBottom: 15,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#EAEAEA",
  },
  postHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 15,
    paddingVertical: 12,
  },
  postHeaderLeft: { flexDirection: "row", alignItems: "center", flex: 1 },
  postAvatar: { width: 44, height: 44, borderRadius: 22, marginRight: 12 },
  postUserText: { fontSize: 16, fontWeight: "700", color: "#111" },
  postGroupText: { fontSize: 14, color: "#888", fontWeight: "500" },
  postLocationText: {
    fontSize: 13,
    color: "#888",
    marginTop: 2,
    paddingRight: 20,
  },
  postMainImage: { width: width, height: width * 0.85 },
  carouselDots: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 12,
  },
  dot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: "#CCC",
    marginHorizontal: 4,
  },
  activeDot: { width: 22, backgroundColor: "#555" },
  postActionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 15,
  },
  postActionLeft: { flexDirection: "row", alignItems: "center" },
  actionIcon: { marginRight: 8 },
  actionText: {
    fontSize: 16,
    color: "#444",
    marginRight: 18,
    fontWeight: "500",
  },
  postTextContainer: { paddingHorizontal: 15, marginTop: 12 },
  postCaptionText: { fontSize: 15, color: "#222", lineHeight: 22 },
  postTimeText: { fontSize: 13, color: "#999", marginTop: 8 },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  bottomSheet: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 20,
    paddingTop: 15,
    paddingBottom: 40,
  },
  sheetHandle: {
    width: 45,
    height: 5,
    backgroundColor: "#DDD",
    borderRadius: 3,
    alignSelf: "center",
    marginBottom: 25,
  },
  sheetActionRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 15,
    gap: 18,
  },
  sheetMainText: { fontSize: 18, fontWeight: "500", color: "#222" },
  sheetSubText: { fontSize: 13, color: "#888", marginTop: 2 },

  formLabel: { fontSize: 16, fontWeight: "700", color: "#333" },
  formSubLabel: { fontSize: 13, color: "#888", marginTop: 3 },
  coverPhotoPlaceholder: {
    width: "100%",
    height: 180,
    backgroundColor: "#CCC",
    borderRadius: 8,
    marginTop: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  addPictureText: {
    color: "#2196F3",
    fontSize: 15,
    fontWeight: "600",
    textAlign: "center",
    marginTop: 10,
  },
  avatarPlaceholder: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "#CCC",
    alignSelf: "center",
    marginTop: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  formInput: {
    width: "100%",
    minHeight: 45,
    backgroundColor: "#F2F2F2",
    borderRadius: 8,
    paddingHorizontal: 15,
    marginTop: 10,
    fontSize: 16,
  },
  toggleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 25,
  },

  captionHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 15,
  },
  boostPostBtn: { flexDirection: "row", alignItems: "center" },
  boostPostText: {
    color: "#E91E63",
    fontWeight: "700",
    fontSize: 15,
    marginLeft: 6,
  },
  captionInputTextarea: {
    width: "100%",
    height: 160,
    backgroundColor: "#F2F2F2",
    borderRadius: 12,
    padding: 15,
    marginTop: 12,
    fontSize: 16,
    textAlignVertical: "top",
  },
  charCountText: {
    textAlign: "right",
    color: "#999",
    fontSize: 13,
    marginTop: 8,
  },
  preferencesHeader: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#111",
    marginTop: 30,
  },
  preferencesDivider: {
    width: "100%",
    height: 1,
    backgroundColor: "#EEE",
    marginTop: 15,
    marginBottom: 5,
  },
  toggleRowPref: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 15,
  },
  postBottomToolbar: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    backgroundColor: "#F9F9F9",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingBottom: 40,
    paddingTop: 15,
    elevation: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
  toolbarHandle: {
    width: 40,
    height: 4,
    backgroundColor: "#DDD",
    borderRadius: 2,
    alignSelf: "center",
    marginBottom: 20,
  },
  toolbarIconRow: {
    flexDirection: "row",
    justifyContent: "flex-start",
    paddingHorizontal: 25,
    gap: 30,
  },

  boostEventContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#FCE4EC",
    padding: 15,
    borderRadius: 8,
    marginTop: 25,
    borderWidth: 1,
    borderColor: "#F8BBD0",
  },
  boostEventTitle: { fontSize: 16, fontWeight: "700", color: "#E91E63" },
  boostEventSub: { fontSize: 13, color: "#E91E63", marginTop: 3 },

  detailHeader: {
    paddingTop: 60,
    paddingHorizontal: 15,
    paddingBottom: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: "#EEE",
  },
  detailHeaderLeft: { flexDirection: "row", alignItems: "center", gap: 6 },
  detailHeaderTitle: { fontSize: 18, fontWeight: "700", color: "#111" },
  detailOwnBadge: {
    backgroundColor: "#DDEEFF",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  detailOwnBadgeText: { color: "#4A81D3", fontWeight: "bold", fontSize: 11 },
  detailHeaderRight: { flexDirection: "row", alignItems: "center" },
  detailMainImage: { width: "100%", height: 260 },
  detailContent: { padding: 20 },
  detailVehicleNameQuote: { fontSize: 16, color: "#555", fontStyle: "italic" },
  detailVehicleModelName: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#111",
    marginTop: 4,
    marginBottom: 20,
  },
  detailCardsList: { gap: 10, marginBottom: 25 },
  detailItemCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F5F5F5",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
  },
  detailIconBox: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#E3F2FD",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 15,
  },
  detailCardText: { flex: 1 },
  detailCardLabel: { fontSize: 14, fontWeight: "bold", color: "#333" },
  detailCardValue: { fontSize: 13, color: "#777", marginTop: 2 },
  detailSectionTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#111",
    marginBottom: 10,
  },
  detailDescriptionText: {
    fontSize: 15,
    color: "#444",
    lineHeight: 22,
    marginBottom: 25,
  },
  detailEmptyModifications: {
    alignItems: "center",
    paddingVertical: 40,
    paddingHorizontal: 20,
    borderStyle: "dashed",
    borderWidth: 1,
    borderColor: "#DDD",
    borderRadius: 12,
    marginTop: 15,
  },
  crossedWrenchesWrapper: {
    width: 50,
    height: 50,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 15,
  },
  detailEmptyModTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    marginTop: 10,
  },
  detailEmptyModSub: {
    fontSize: 13,
    color: "#888",
    textAlign: "center",
    marginTop: 5,
  },
  detailModificationsList: { marginTop: 10 },
  modificationItemCard: {
    backgroundColor: "#FFF",
    padding: 15,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#EEE",
    marginBottom: 12,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  modItemHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  modItemName: { fontSize: 16, fontWeight: "bold", color: "#111" },
  modClassificationBadge: {
    backgroundColor: "#E8F5E9",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  modClassificationText: { color: "#2E7D32", fontSize: 11, fontWeight: "bold" },
  modItemDesc: { fontSize: 14, color: "#555", marginTop: 8, lineHeight: 20 },
  modItemLink: {
    fontSize: 13,
    color: "#2196F3",
    marginTop: 8,
    textDecorationLine: "underline",
  },

  addModHeader: {
    paddingTop: 50,
    height: 95,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#EEE",
    backgroundColor: "#FFF",
  },
  addModHeaderLeft: { width: 50, justifyContent: "center" },
  addModHeaderTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#111",
    textAlign: "center",
    flex: 1,
  },
  addModHeaderRight: {
    width: 50,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  addModSaveText: { fontSize: 16, fontWeight: "600" },
  modFormLabel: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#222",
    marginTop: 18,
  },
  modFormInput: {
    width: "100%",
    minHeight: 45,
    backgroundColor: "#F2F2F2",
    borderRadius: 12,
    paddingHorizontal: 15,
    marginTop: 8,
    fontSize: 16,
    color: "#333",
  },
  modCharCounterInside: {
    position: "absolute",
    top: 20,
    right: 15,
    color: "#999",
    fontSize: 12,
    fontWeight: "500",
  },
  catModalWrapper: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 40,
  },
  catModalContent: {
    backgroundColor: "#FFF",
    borderRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 25,
    width: "100%",
    maxHeight: "85%",
    elevation: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
  },
  catSearchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF",
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
    paddingBottom: 10,
    marginBottom: 10,
  },
  catSearchInput: { flex: 1, fontSize: 16, color: "#333", padding: 0 },
  catHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: 15,
    paddingBottom: 10,
  },
  catHeaderTitle: { fontSize: 18, fontWeight: "bold", color: "#111" },
  catItemRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
  },
  catItemText: { fontSize: 16, color: "#555" },
  catItemTextSelected: { color: "#111", fontWeight: "bold" },
  catConfirmButton: {
    backgroundColor: "#007AFF",
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 15,
  },
  catConfirmButtonText: { color: "white", fontSize: 16, fontWeight: "600" },
  vMenuOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  vMenuBottomSheet: {
    backgroundColor: "#FFF",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 40,
  },
  vMenuHandle: {
    width: 45,
    height: 5,
    backgroundColor: "#DDD",
    borderRadius: 3,
    alignSelf: "center",
    marginBottom: 25,
  },
  vMenuActionRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
    gap: 16,
  },
  vMenuText: {
    fontSize: 18,
    fontWeight: "500",
    color: "#222",
  },
  vehiclesHeader: {
    paddingTop: 60,
    paddingHorizontal: 15,
    paddingBottom: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: "#EEE",
  },
  vehiclesHeaderLeft: {
    padding: 6,
  },
  vehiclesHeaderTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111",
  },
  vehiclesGridContainer: {
    padding: 16,
    paddingBottom: 40,
  },
  vehiclesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  vehiclesGridCard: {
    width: (width - 44) / 2,
    height: 160,
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: "#DDD",
  },
  vehiclesGridImage: {
    width: "100%",
    height: "100%",
  },
  vehiclesGridOwnBadge: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: "#DDEEFF",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  vehiclesGridOwnBadgeText: {
    color: "#4A81D3",
    fontWeight: "bold",
    fontSize: 11,
  },
  vehiclesGridOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    padding: 10,
  },
  vehiclesGridName: {
    color: "white",
    fontSize: 15,
    fontWeight: "bold",
  },
  vehiclesGridModel: {
    color: "rgba(255,255,255,0.8)",
    fontSize: 11,
    marginTop: 2,
  },
});
